### ISSUE TITLE
semipair_loss_layer.cpp

### ISSUE THREAD

**Issue by Xinguo806** [PKU-ICST-MIPL/SSDH_TCSVT2017#1]
This file is missing, could you provide it asap....

**Comment by Xinguo806** [comment]
semipair_loss_layer.cpp is missing, could you provide it asap...

**Comment by PKU-ICST-MIPL** [comment]
semipair_loss_layer.cpp is not required in this code, but you can find this file in https://github.com/PKU-ICST-MIPL/QaDWH_TMM2018
the command "make test" will be failed, but you can follow the steps in README to run our codes.

**Comment by Xinguo806** [comment]
Thanks for your reply, there is a new problem arises,  one folder  named  "hdf5" under the path of data/flickr25k is missing, the semitrain_multi_label_h5.list  in this folder is requried in the codes, so could you kindly solve this new problem again?
ps: When I copy semipair_loss_layer.cpp and semipair_loss_layer.cn in this code, the command "make test" is still failed, but if I remove test_semipair_loss_layer.cpp away, make test is successful, which make me a bit confused...but, anyway, this is not the immediate problem...

**Comment by PKU-ICST-MIPL** [comment]
> Thanks for your reply, there is a new problem arises, one folder named "hdf5" under the path of data/flickr25k is missing, the semitrain_multi_label_h5.list in this folder is requried in the codes, so could you kindly solve this new problem again?
> ps: When I copy semipair_loss_layer.cpp and semipair_loss_layer.cn in this code, the command "make test" is still failed, but if I remove test_semipair_loss_layer.cpp away, make test is successful, which make me a bit confused...but, anyway, this is not the immediate problem...

The flickr25k_semitrain_multi_label_h5.list is list of h5 file path. The h5 file contains multi label for the images, which is denoted as a vector, for example, (0,0,0,1,1,0,0,0,0,0,0,0,1,0 ...). For more details, see the code of the multi_label layer.
